### ISSUE TITLE
Game installation detection does not work

### ISSUE THREAD

**Issue by Skyline404** [FriendsOfGalaxy/galaxy-integration-epic#9]
**Describe the bug**
Game installation status is not shown in gog, when try to install/launch the game it just opens epic launcher and nothing more

**Attached logs**
[plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log](https://github.com/FriendsOfGalaxy/galaxy-integration-epic/files/4842465/plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log)

**Comment by FriendsOfGalaxy** [comment]
Hi @Skyline404 

installing
- currently there is no other way to install game as open your epic library and let you choose game manually. Even Epic do that after you buy a game via their Launcher.

launching
-  I do not see in your logs that you tried. Can you try again and paste logs them please?

**Comment by Skyline404** [comment]
Gog tries to install the game, but the game is already installed. heres video and new logs
https://youtu.be/HdCVMRZCA1c
[plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log](https://github.com/FriendsOfGalaxy/galaxy-integration-epic/files/4848227/plugin-epic-24d5f405-7211-4198-83c4-50a6f63b1dcf.log)

**Comment by FriendsOfGalaxy** [comment]
@Skyline404 thanks for more info! 

I see that there is problem with reading this file: `C:\ProgramData\Epic\UnrealEngineLauncher\LauncherInstalled.dat` 
Can you upload it here (you can rename to txt because github does not allow `dat` probably)?

Does this GTA V uses Rockstar launcher to run the game or directly via EpicGamesLauncher? If it uses Rockstar launcher, can you paste content of 

`C:\ProgramData\Epic\EpicGamesLauncher\Data\ThirPartyManagedApps` ?

**Comment by Skyline404** [comment]
Heres dat file. But there no ThirPartyManagedApps folder. I can launch game from playnite as always if this infromation will be useful/
[LauncherInstalled.txt](https://github.com/FriendsOfGalaxy/galaxy-integration-epic/files/4856693/LauncherInstalled.txt)

**Comment by Skyline404** [comment]
The problem was in Russian characters.
Solved

**Comment by FriendsOfGalaxy** [comment]
Right, but this should be open until fix in the code

**Comment by FriendsOfGalaxy** [comment]
Closing as GOG has official integration now. GOG is informed about all remaining issues.
